<a href="https://colab.research.google.com/github/nirupamgangurde/Machine_Learning/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

In [2]:
numpy.array([1,2,3]) #This is one D array

array([1, 2, 3])

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
b = np.array([[1,2,3],[4,5,6]]) # This is 2D array

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b.shape # Here 2 is no of rows and 3 is no of columns

(2, 3)

In [9]:
b.shape[0] # extracting 1st value of the shape that is 2

2

In [10]:
b*4 # This multiplies the each element in array with 4

array([[ 4,  8, 12],
       [16, 20, 24]])

In [11]:
b**2 # This will give you square of each element of b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [12]:
a.shape # Bcz this is 1 D array

(3,)

In [13]:
b.dtype # to check datatype

dtype('int64')

In [14]:
b.ndim # this will tell you no of dimentions array have

2

In [15]:
a.ndim

1

In [16]:
print(type(a))

<class 'numpy.ndarray'>


In [17]:
print(type(b))

<class 'numpy.ndarray'>


In [18]:
[i for i in range(0,51,2)] # This will print the list of no from 0 to 51 having gap of 2

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50]

In [19]:
np.arange(10) # In this we have 3 parameters that is np.arange(start,last-1,step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,51,2) # arange means array range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [21]:
c = range(10000)
%timeit [i**3 for i in c] # %timeit used to display runtime this result is using normal python

2.03 ms ± 465 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
c_numpy = np.arange(10000)
%timeit c_numpy**3 #this is using numpy and numpy is fast bcz it is written in c lang.

110 µs ± 25.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Creating numpy array and performing diff actions on it

In [23]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [25]:
np.zeros((3,2)) # This creats a matrix of 3 rows and 2 columns with all the zero values init

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
np.zeros(10) # Wil print 1d array having 10 zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
np.eye(3) # As we have passed value 3 so it will create a 3*3 matrix having diagonal 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.full((3,3),2) # will create 3*3 array and all values are 2 only

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [30]:
np.full((3,3),2.2, dtype =int) # same working just we are doing typecasting here where 2.2 is float value and we are converting it into Int value

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [31]:
np.diag([1,2,3,4,5]) # Will print values diagonally in 1 to n th array

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [32]:
v = np.array([1,2,3])

In [33]:
np.tile(v,(3,1)) # stack 3 copies of v on top of each other 3 row 1 column

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [34]:
import random

In [35]:
np.random.random() # this will give you value between 0 to 1

0.722649854820728

In [36]:
50*np.random.random()+2 # This will give you a random value between 2 to 50

51.59392314857475

In [37]:
np.random.random([3,3]) # will give you 3*3 matrix array

array([[0.66477899, 0.74478595, 0.30617255],
       [0.07048153, 0.84035943, 0.8548621 ],
       [0.47723658, 0.32495168, 0.04332146]])

In [38]:
a = np.linspace(1,50,100) # 100 values between 1 to 50 which have equal space in between

In [39]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [40]:
a.shape

(100,)

In [42]:
a.reshape(25,2,2) # reshaped this array in 25 blocks 2rows in each block and each row contain 2 elements

array([[[ 1.        ,  1.49494949],
        [ 1.98989899,  2.48484848]],

       [[ 2.97979798,  3.47474747],
        [ 3.96969697,  4.46464646]],

       [[ 4.95959596,  5.45454545],
        [ 5.94949495,  6.44444444]],

       [[ 6.93939394,  7.43434343],
        [ 7.92929293,  8.42424242]],

       [[ 8.91919192,  9.41414141],
        [ 9.90909091, 10.4040404 ]],

       [[10.8989899 , 11.39393939],
        [11.88888889, 12.38383838]],

       [[12.87878788, 13.37373737],
        [13.86868687, 14.36363636]],

       [[14.85858586, 15.35353535],
        [15.84848485, 16.34343434]],

       [[16.83838384, 17.33333333],
        [17.82828283, 18.32323232]],

       [[18.81818182, 19.31313131],
        [19.80808081, 20.3030303 ]],

       [[20.7979798 , 21.29292929],
        [21.78787879, 22.28282828]],

       [[22.77777778, 23.27272727],
        [23.76767677, 24.26262626]],

       [[24.75757576, 25.25252525],
        [25.74747475, 26.24242424]],

       [[26.73737374, 27.23232323],
  

In [43]:
a.reshape(25,2,2).shape

(25, 2, 2)

In [44]:
np.arange(24).reshape(2,4,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [45]:
np.arange(24).reshape(2,4,-1).shape

(2, 4, 3)

How to access numpy array element


In [46]:
a = np.array([2,4,6,8,10,12,14,16])

In [47]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [48]:
a[2] # accessing element using indexing

np.int64(6)

In [49]:
a[[2,4,6]] # This will access 2nd 4th and 6th value

array([ 6, 10, 14])

In [50]:
a[2:]

array([ 6,  8, 10, 12, 14, 16])

In [51]:
a[2:5]

array([ 6,  8, 10])

In [52]:
a[0::2] # a[start:stop:step] step : how many steps to move each time

array([ 2,  6, 10, 14])

For 2D array

In [53]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
a[2,2] # 1st two means the 2nd row and 2nd two means 2nd column anything you are writing before comma is for row and after comma it is for column

np.int64(9)

In [57]:
a[:2:,1::] # start:stop:step
#Row Slice → :2:
# Start: not specified → starts from index 0
# Stop: 2 → stops before index 2 (i.e., includes index 0 and 1)
# Step: not specified → default is 1
# → Picks rows at index 0 and 1

# Column Slice → 1::
# Start: 1 → starts from column index 1
# Stop: not specified → goes till end
# Step: not specified → default is 1
# → Picks columns from index 1 to the end

array([[2, 3],
       [5, 6]])

In [58]:
a[:1:,1::]

array([[2, 3]])

In [59]:
a>2 # displays the condition is true or false for each element

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [60]:
a[a>2] #prints the values grater than 2 it is kind of filter

array([3, 4, 5, 6, 7, 8, 9])

In [61]:
a[(a>2) & (a<5)]

array([3, 4])

Subsets of numpy array

In [62]:
a = np.arange(10)

In [63]:
b = a

In [64]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
b[0] = 11

In [66]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [67]:
a #a also get changed

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [68]:
a = np.arange(10)
b = a.copy()
b[0]= 15
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[15  1  2  3  4  5  6  7  8  9]


Transposition of matrix

In [69]:
a = np.array([[1,2,3],[4,5,6]])

In [70]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.transpose(a) # Converts rows to column and column to row

array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [73]:
b = np.array([[7,8,9],[10,11,12]])

In [74]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [76]:
a == b # Compares each element in the array

array([[False, False, False],
       [False, False, False]])

In [77]:
np.vstack((a,b)) # Here we are appending two arrays this is vertical stack like a/b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
np.hstack((a,b)) # Here we are appending the two arrays this is horizontal stack like a + b

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])