<a href="https://colab.research.google.com/github/nirupamgangurde/Machine_Learning/blob/main/Pandas_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
a = pd.Series([1,2,3,4,5,6,7,8,9,10]) #this will start assigning a index to each element and hence we have only one column with values is known as series.

In [5]:
a

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [6]:
type(a)

pandas.core.series.Series

In [7]:
a[2] # index 2

np.int64(3)

In [8]:
a = pd.Series(['a','b','c'])

In [9]:
a

0    a
1    b
2    c
dtype: object

In [10]:
a = pd.date_range(start = '01-01-2018',end = '23-5-2018') #creating date range here

In [11]:
a

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08',
               '2018-01-09', '2018-01-10',
               ...
               '2018-05-14', '2018-05-15', '2018-05-16', '2018-05-17',
               '2018-05-18', '2018-05-19', '2018-05-20', '2018-05-21',
               '2018-05-22', '2018-05-23'],
              dtype='datetime64[ns]', length=143, freq='D')

In [12]:
type(a)

pandas.core.indexes.datetimes.DatetimeIndex

Pandas Dataframe

In [13]:
import numpy as np

In [14]:
temp = np.random.randint(low = 20, high = 100, size = [20,])
name = np.random.choice(['Abhay','Teclov','Geekshub','Aniket'],20)
random = np.random.choice([10,11,13,12,14],20)

In [15]:
temp

array([46, 35, 31, 68, 31, 74, 99, 60, 84, 77, 25, 20, 42, 40, 23, 53, 27,
       86, 84, 68])

In [16]:
name

array(['Geekshub', 'Geekshub', 'Aniket', 'Aniket', 'Aniket', 'Aniket',
       'Aniket', 'Teclov', 'Abhay', 'Aniket', 'Abhay', 'Teclov', 'Teclov',
       'Teclov', 'Teclov', 'Teclov', 'Teclov', 'Aniket', 'Abhay',
       'Geekshub'], dtype='<U8')

In [17]:
random

array([13, 12, 12, 11, 11, 14, 10, 13, 10, 11, 11, 10, 10, 10, 12, 12, 12,
       14, 10, 11])

In [23]:
a = list(zip(temp, name, random)) # taking each value sequentially from the all arreys and making a list of arrays
a[:5]

[(np.int64(46), np.str_('Geekshub'), np.int64(13)),
 (np.int64(35), np.str_('Geekshub'), np.int64(12)),
 (np.int64(31), np.str_('Aniket'), np.int64(12)),
 (np.int64(68), np.str_('Aniket'), np.int64(11)),
 (np.int64(31), np.str_('Aniket'), np.int64(11))]

In [24]:
df = pd.DataFrame(data = a, columns=['temp','name','random']) #creating dataframe and naming columns
df

temp      name  random
0     46  Geekshub      13
1     35  Geekshub      12
2     31    Aniket      12
3     68    Aniket      11
4     31    Aniket      11
5     74    Aniket      14
6     99    Aniket      10
7     60    Teclov      13
8     84     Abhay      10
9     77    Aniket      11
10    25     Abhay      11
11    20    Teclov      10
12    42    Teclov      10
13    40    Teclov      10
14    23    Teclov      12
15    53    Teclov      12
16    27    Teclov      12
17    86    Aniket      14
18    84     Abhay      10
19    68  Geekshub      11

In [25]:
df[:5] # this will give you a rows basis on index

temp      name  random
0    46  Geekshub      13
1    35  Geekshub      12
2    31    Aniket      12
3    68    Aniket      11
4    31    Aniket      11

In [26]:
df["temp"] [:5] # how to extract single column data using indexing

0    46
1    35
2    31
3    68
4    31
Name: temp, dtype: int64

In [27]:
df["temp"].values # will give you values in array form

array([46, 35, 31, 68, 31, 74, 99, 60, 84, 77, 25, 20, 42, 40, 23, 53, 27,
       86, 84, 68])

In [30]:
df["temp"].max() # max value in temp column this type of functions can be only applied on series data

99

In [31]:
df["temp"].min()

20

In [32]:
df["temp"].sum()

np.int64(1073)

In [33]:
df["temp"].std()

24.83053086741995

In [34]:
df[["temp","name"]]   # When if you have more column name to extract at that time we use list means double square bracket

temp      name
0     46  Geekshub
1     35  Geekshub
2     31    Aniket
3     68    Aniket
4     31    Aniket
5     74    Aniket
6     99    Aniket
7     60    Teclov
8     84     Abhay
9     77    Aniket
10    25     Abhay
11    20    Teclov
12    42    Teclov
13    40    Teclov
14    23    Teclov
15    53    Teclov
16    27    Teclov
17    86    Aniket
18    84     Abhay
19    68  Geekshub